### ISSUE TITLE
First Day

### ISSUE THREAD

**Issue by arpit-dwivedi** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#1]
Hello,
Summarize your today's work in by commenting below.

> Do not describe in brief, just mention the steps you performed in the list format (100-200 words).

**Comment by Ansuman9020** [comment]
- I have to make a simple landing page in bootstrap studio.
- The page made by me includes home page, contact us part, team members description and even the footer.
- We are asked to use the drag and drop feature.
- I just used the header dark mode where I just changed the company name and included nav items there. Added a search area in the home page.
- Next to that added a team section which includes the description of the team along with their social link as well as their designation in the comapny.
- The next section was the contact us section.
- Then I added the footer which provied with the social links,  services provided by the company, links to different parts and a short desciption of the page and botton to that it includes a copyright column.
- This the task done today and even I trailed different components on the page and apperances on the body. Got an overview to work with bootstrap studio.

**Comment by akshayadme** [comment]
- First I have downloaded the Bootstrap Studio and go through it about its services.
- In that I have created a landing page initially form page using drag and drop feature of bootstrap studio. 
- I have created first Navbar with brand-name some quick links and a button in it.
- Next step is to create home section of it with some heading, texts and a button.
- Later I created a footer section with some social media links and copyright section.
- Today's task has been completed and I have learned something new from it. I can now hands on to bootstrap studio.

**Comment by reddymahendra52** [comment]
* Today's task was to make a simple landing page with the help of Bootstrap Studio.
* First I made the outline of my page like how I wanted my page to look  in general so that it can be easy while coding.
* My page contains a header which contains a responsive Navbar.
* After the header there is a main section which contains all the other sections which are basically the about section, feature section, image section and a video section.
* At the bottom there is a contact us section with a form.
* At the end there are social media links and a copyright column.
* Bootstrap studio has a nice feature of drag and drop and many other cool features which are easy to use.
* In the start I had a bit of problem understanding how things work in Bootstrap studio, after understanding what goes where and where to find the required things its really easy to use
* Today in a gist created a simple basic landing page and learnt, understood **Bootstrap Studio.**

**Comment by manvi-123894** [comment]
1. For the first task, we were instructed to install the Bootstrap Studio and make a landing page.
 2. I created a simple landing page using bootstrap studio which includes a navigation bar, home section, about, services, gallery, and a footer.
3. The navigation bar contains the logo of the website and some links to different sections of the web page.
4. For the home section, I used a jumbotron with a heading and a small intro about the web page. For about section, I simply used a heading and a paragraph.
5. For services and gallery, I used responsive grid layout with images and font-awesome icons. 
6. The footer section contains the contact details of the owner of the website.
7. From this task, I learnt how to use the bootstrap studio and create web pages in no-time.

**Comment by chirag0821** [comment]
- In today's task I have to make a landing page using bootstrap studio.
- First I have downloaded the bootstrap studio and learned all the sections in the software and all the features of it.
- I made outline of the complete landing page of  cake delivery website in my mind first.
- After that I added the navbar first which contains price, order, cakes and contact us sections.
- Then I added background image to the complete webpage.
- I added main heading and a paragraph and styled it by CSS code.
- Then I created cards showing images of the cakes and its price.
- At the bottom I created contact us section and order section.
- later I created footer section with my website logo and social media links.
- Today I got the complete overview of bootstrap studio now I can make many web-pages using this.

**Comment by mahakal420** [comment]
**For the first task, we were instructed to install the Bootstrap Studio and create the personal portfolio**
**Firstly I have learned all the basics of bootstrap studio **
**  I used an inbuilt bootstrap studio template to create my portfolio which is very easy to use, then creating it from scratch.**

**Comment by mahakal420** [comment]
-  First task is to install bootstrap studio and create a personal portfolio.
-   I go through the basic documentation of bootstrap studio and learn about its features.
-   I used an inbuilt bootstrap studio template to create my portfolio.
- The template contains a header, hero section, about, projects, and contact. We have to make some changes to it and then add details about ourselves to it.

**Comment by KunalMahato11** [comment]
* In the first week's task, we were assigned to make our own portfolio website using the bootstrap studio.
* First, I downloaded the bootstrap studio. I explored it inside out, where I learned to navigate the software and structure basic web pages—stuff like how to create divs, headers, sections, and how to apply styles to them, how to align and how to use flexbox properties.
* Then, I created a new design and loaded the freelancer portfolio template that we get for free to use.
* I added the skills set section to the header, changed the title, updated the about section, added the project section, updated social media links, etc. 
* I got the complete overview of the bootstrap studio and proper hands-on experience.

Bootstrap file : 
[Portfolio-Website.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/6090890/Portfolio-Website.zip)

**Comment by Ritika-Agrawal811** [comment]
1. Task One includes downloading Bootstrap Studio and building a portfolio using it.
2.  I download the software and then watched videos to explore its various features.
3. I learned to add different html elements and style it using the interface provided by Bootstrap studio.
4. I added various images and tried to add hover effects on them.
5. I explored the different templates available and explored the way html elements were grouped together in them.
6. I also learned to work with navbar.

Bootstrap file of my portfolio->
[Portfolio.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/6111407/Portfolio.zip)

**Comment by NihalSuresh007** [comment]
The first task assigned to us was we were instructed to install the Bootstrap Studio and create a portfolio page.
I created a simple portfolio page using bootstrap studio which includes a navigation bar, home section, about, services, and a footer.
The navigation bar contains the name of the website and some links to different sections of the web page.
I added the different photos and sections needed in the portfolio page.
The footer section contains the contact details of the owner of the website.
From this task, I learnt how to use the bootstrap studio and create web pages in no-time.
[Portfolio.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/6114716/Portfolio.zip)

**Comment by mahakal420** [comment]
- In the first week's task, we were assigned to make our own portfolio website using the bootstrap studio.
- First I have to download the software and then watched videos to explore its various features.
- Then edited the template portfolio.
- I got a complete overview of the bootstrap studio and proper hands-on experience.

Bootstrap file
[portfolio.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/6115391/portfolio.zip)

**Comment by RohitsSkill** [comment]
1. As per the task first I download bootstrap studio and then install it.
2.  Then I learn some basic things related to bootstrap studio.
3. After that I have created my portfolio with the help of template provided by them
4. This task help  me to understand bootstrap studio.
[Portfolio.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/6124984/Portfolio.zip)

**Comment by abhishekpatelmc** [comment]
### Starting with Bootstrap
I have worked with Bootstrap before , but i had not experience the easy flow which bootstrap studio provides. All the the things can be drag-dropped to the the layout. CSS can be made custom. Best part about Bootstrap is that the website are responsive from the beginning.
