### ISSUE TITLE
#11 Designing Blog Pages

### ISSUE THREAD

**Issue by reddymahendra52** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#11]
Today's task is to design different blog pages for different topics using the same previous template.

@akshayadme    : Authors' Page
@Ansuman9020 : ML Blog Page
@reddymahendra52 : OpenCV Blog Page 
@manvi-123894  : Python Blog Page
@chirag0821 : NLP Blog Page

**Comment by reddymahendra52** [comment]
* Today's task was to create a blog page for the OpenCV
* I created the page which matches the reference template
[OpenCV Blog page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5329101/OpenCV.Blog.page.zip)

**Comment by akshayadme** [comment]
I have designed Authors page

[authors bsdesign.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5329161/authors.zip)

[authors exported page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5329228/authors.page.zip)

**Comment by manvi-123894** [comment]
- My task for today was to create the page for python blogs.

- I've just created the structure for the content.
[Python_blog_page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5329285/Python_blog_page.zip)

**Comment by chirag0821** [comment]
- My task was create structure for NLP blog pages.
- I created the structure, it is responsible and matching to the main site.
[NLP blog](https://drive.google.com/u/0/uc?id=1V9koZmbSODKdX3TYfKiRuwP7f32Puxph&export=download)

**Comment by Ansuman9020** [comment]
- Sorry for the late submission, as there was a electricity cutdown from yesterday so I did it today morning.
[New folder.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5331448/New.folder.zip)

**Comment by reddymahendra52** [comment]
* Today's task was to recreate the blog page which was created yesterday
* I totally build a new blog page from scratch
* I used a lot of custom code to rebuild the page
* Since I mostly used the custom code first just created the bsdesign with just integrated parts of code without styling
* After exporting I did the styling
[Final OpenCV.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5334405/Final.OpenCV.zip)

**Comment by manvi-123894** [comment]
- Today's task was to improve the previously made blog page for python.
[Python_Blog_Page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5335029/Python_Blog_Page.zip)

**Comment by akshayadme** [comment]
I have updated the authors page by adding dropdown menu for authors article.

[authors page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5335491/authors.page.zip)

**Comment by Ansuman9020** [comment]
Updated the previous without header and footer.
[blog.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5335745/blog.zip)

**Comment by chirag0821** [comment]
- Today updated the page with blog sections.
[NLP.zip](https://drive.google.com/u/0/uc?id=1BrrzwNJz6s3s7otJ6sEV7oMYlKkDoatL&export=download)
