### ISSUE TITLE
Summary of the work.

### ISSUE THREAD

**Issue by arpit-dwivedi** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#15]
Please summarize all the work done by you during the internship  in brief with links of your work.

**Comment by akshayadme** [comment]
- Initially we have downloaded and installed Bootstrap Studio application and learn and understand about it for designing static website using drag and drop feature of application. In the application there is multiple templates available for designing web pages.

- After understanding about bootstrap studio my first task was to design landing page as a learning purpose. In that I have designed navbar, some sections, and a footer in a page.

- My second task was to understanding about SEO in webpages and then commented an issue in github.

- Next task was to build personal portfolio using bootstrap studio and publish it using github static pages. My personal portfolio  link is [here](https://akshayadme.github.io/Personal-Portfolio/)

- Next task was to design technical article for blog for DevIncept blog website and I have designed about python article whose link is [here](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/5#issuecomment-699019182)

- My personal next task to design template of DevIncept main site home page by adding all of the sections so I have implement it [here](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/7#issuecomment-700004581)

- In next task I have updated my home page design and make the template for DevIncept blog website which is present [here](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/9#issuecomment-701452126)

- Next task was for work individually as previously common task was given and from now individually we have to work so my task was to design authors page for blog website so what I have designed is [here](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/11#issuecomment-703789104).

- Next we had to comment for what help we will need for developing blog website from technical persons for making an effective static blog pages.

- Next we had to make a try for implementing "Search Feature" in static website in which we have tried but we didn't reach at any particular conclusion for it.

- Next as everyone was working individually and everyone had designed there task for blog page so my task was to integrate all pages and then give it a final look and then add SEO in it. [here](https://devinceptworkspace.slack.com/archives/G01BE7ZHEC9/p1602478640000400)

**Comment by kanchitank** [comment]
- **Understanding Flask and building a simple application** - [Link](https://github.com/Learn-Write-Repeat/Open-contributions/issues/175#issuecomment-705523678)

- **ML Model Deployment Using Flask** - [Link](https://github.com/Learn-Write-Repeat/Open-contributions/issues/175#issuecomment-705523678)

- **Gender Classification Web App Using Flask** - [Link](https://github.com/Learn-Write-Repeat/Contribution-program/tree/master/ML_models_Flask/Kanchi_Tank)

- **Categorized all the ML topics** - [Link](https://github.com/Learn-Write-Repeat/ml/blob/main/topics.pdf)

- **Created 16 folders in the ML repository containing all the ML data** - [Link](https://github.com/Learn-Write-Repeat/ml)

- **Open contributions** - [Link1](https://github.com/Learn-Write-Repeat/Open-contributions/blob/master/KanchiTank_ML_Classification.md), [Link2](https://github.com/Learn-Write-Repeat/Open-contributions/blob/master/KanchiTank_ML_Classification.ipynb)

**Comment by kanchitank** [comment]
- **Understanding Flask and building a simple application** - [Link](https://github.com/Learn-Write-Repeat/Open-contributions/issues/175#issuecomment-705523678)

- **ML Model Deployment Using Flask** - [Link](https://github.com/Learn-Write-Repeat/Open-contributions/issues/175#issuecomment-705697294)

- **Gender Classification Web App Using Flask** - [Link](https://github.com/Learn-Write-Repeat/Contribution-program/tree/master/ML_models_Flask/Kanchi_Tank)

- **Categorized all the ML topics** - [Link](https://github.com/Learn-Write-Repeat/ml/blob/main/topics.pdf)

- **Created 16 folders in the ML repository containing all the ML data** - [Link](https://github.com/Learn-Write-Repeat/ml)

- **Open contributions** - [Link1](https://github.com/Learn-Write-Repeat/Open-contributions/blob/master/KanchiTank_ML_Classification.md), [Link2](https://github.com/Learn-Write-Repeat/Open-contributions/blob/master/KanchiTank_ML_Classification.ipynb)

**Comment by aditya9110** [comment]
- [Understanding Flask](https://github.com/Learn-Write-Repeat/Open-contributions/issues/175#issuecomment-704061933)
- [To Do List App](https://github.com/aditya9110/ToDo-List-App)
- [ML Model Deployment using Flask](https://github.com/Learn-Write-Repeat/Open-contributions/issues/175#issuecomment-705085452)
- [Loan Eligibility System using Flask](https://github.com/Learn-Write-Repeat/Contribution-program/tree/master/ML_models_Flask/Aditya%20Mahimkar)
- [Deployment using Heroku](https://loan-eligibility-system.herokuapp.com)
- Data Curation of NLP domain
  1. [TF IDF](https://github.com/Learn-Write-Repeat/nlp/tree/main/TF%20IDF)
  2. [Sentiment Analysis](https://github.com/Learn-Write-Repeat/nlp/tree/main/Sentiment%20Analysis)
  3. [Topic Modelling](https://github.com/Learn-Write-Repeat/nlp/tree/main/Topic%20Modelling)
  4. [Lemmatization And Stemming](https://github.com/Learn-Write-Repeat/nlp/tree/main/Lemmatization%20And%20Stemming)
  5. [Word Embedding](https://github.com/Learn-Write-Repeat/nlp/tree/main/Word%20Embedding)
  6. [NLP using Pytorch](https://github.com/Learn-Write-Repeat/nlp/tree/main/NLP%20using%20Pytorch)
  7. [NLP using SkLearn](https://github.com/Learn-Write-Repeat/nlp/tree/main/NLP%20using%20SkLearn)

**Comment by Rishav-hub** [comment]
- Understanding the Basics of Flask [here][link1].
- Also contributed to Hacktoberfest2020 [here][link2].
- Learnt the concept of Text extraction using Tesseract [here][link3].
- Implemented a basic text extraction using OCR concepts [here][link4].
- Learnt how to deploy an Object Detection Project using Flask [here][link5].

[link1]: https://github.com/Rishav-hub/flask_basics.git
[link2]: https://github.com/Learn-Write-Repeat/Open-contributions.git
[link3]: https://github.com/Learn-Write-Repeat/Contribution-program/issues/24
[link4]: https://github.com/Learn-Write-Repeat/Contribution-program/issues/24
[link5]: https://github.com/Learn-Write-Repeat/Contribution-program/blob/master/intern-basics/object_detection_flask_deployment.md

**Comment by anillko1108** [comment]
- [**Understanding Flask and small application with it**](https://github.com/Learn-Write-Repeat/Open-contributions/issues/175#issuecomment-704077163)

- [**Deploy Machine Learning Model Using Flask**](https://github.com/Learn-Write-Repeat/Open-contributions/issues/175#issuecomment-705306269)

-  [**Sales prediction web application using flask**](https://github.com/Learn-Write-Repeat/Contribution-program/tree/master/ML_models_Flask/Anil%20Kumar%20Mishra%20AI)

- **Data Curation**
       - [Naïve Bayes Classifier Algorithm](https://github.com/Learn-Write-Repeat/nlp/tree/main/Na%C3%AFve%20Bayes%20Classifier%20Algorithm)
       - [Word2Vec](https://github.com/Learn-Write-Repeat/nlp/tree/main/Word2Vec)
       - [LSTM](https://github.com/Learn-Write-Repeat/nlp/tree/main/LSTM)
       - [RNN](https://github.com/Learn-Write-Repeat/nlp/tree/main/RNN)
       - [Bag of Words](https://github.com/Learn-Write-Repeat/nlp/tree/main/Bag%20of%20Words)
       - [Subsampling](https://github.com/Learn-Write-Repeat/nlp/tree/main/Subsampling)
       - [Word2Vec](https://github.com/Learn-Write-Repeat/nlp/tree/main/Word_2_Vec)

**Comment by madalatrivedh20** [comment]
<ul><li>Live Sketching app using OpenCV and Python - <a href="https://github.com/Learn-Write-Repeat/Contribution-program/blob/master/intern-basics/Part-5%20Simplesketchapp.md"> Link</a></li></li>
<li>Next word prediction using RNN /LSTM - <a href="https://github.com/madalatrivedh20/Contribution-program/tree/master/trivedh/nextwordpredictor"> Link</a></li>

<li> Data Curation<ul><li>Basic openCV operations- <a href="https://github.com/Learn-Write-Repeat/cv/tree/main/Opencv_basics"</li>> Link</a></li>
<li> Face emotions detector- <a href="https://github.com/Learn-Write-Repeat/cv/tree/main/Faceemotionsdetector"> Link</a></li>
<li> OpenCV SIFT- <a href="https://github.com/Learn-Write-Repeat/cv/tree/main/OpencvSIFT"> Link</a> </li>
<li> Object detection and all other projects of Neelesh - <a href="https://github.com/Learn-Write-Repeat/cv/tree/main/Object%20Detection%20and%20Tracking/neelesh"> Link</a></li>
<li> Video Analysis- <a href="https://github.com/Learn-Write-Repeat/cv/tree/main/Video%20Analysis"> Link</a></li>
<li> Blurring and Sharpening- <a href="https://github.com/Learn-Write-Repeat/cv/tree/main/Blurring%20and%20Sharpening"> Link</a></li></li></ul>

**Comment by john-2424** [comment]
My Work Summary: 

- [Understanding Flask](https://github.com/Learn-Write-Repeat/Open-contributions/issues/175#issuecomment-704086100) : 

Learnt about a web framework called "Flask". It is a micro web framework which can add application features or develop and support web applications. It is based upon Pocco projects such as Werkzeug and Jinja2.

- [Next Word Predictor using LSTM and PyTorch](https://github.com/KrishnaRajule/Contribution-program/tree/master/NextWordPredictor/Krishna_Rajule) : 

**Next Word Predictor** is a useful tool where it will assist us in writing emails, texts messages, also used in search engines, programming text editors, text documents such as MS Word and it is a Language Model which acts as the most common and important precursor to Voice Recognition. This application is being built using **RNN - LSTM** model and **PyTorch** libraries. Please visit the above link for project update.
  
- [Data Curation of OpenCV Projects](https://github.com/KrishnaRajule/cv) : 

Curated OpenCV data from [Open Contribution](https://github.com/Learn-Write-Repeat/Open-contributions) which included the OpenCV projects on [Depth Mapping](https://github.com/KrishnaRajule/cv/tree/main/Depth%20Mapping), [Face Expression Recognition](https://github.com/KrishnaRajule/cv/tree/main/Face%20Expression%20Recognition), [Face Detection](https://github.com/KrishnaRajule/cv/tree/main/Face%20detection), [Image Filtering](https://github.com/KrishnaRajule/cv/tree/main/Image%20Filtering), [Object Detection and Tracking](https://github.com/KrishnaRajule/cv/tree/main/Object%20Detection%20and%20Tracking), [People Count](https://github.com/KrishnaRajule/cv/tree/main/People%20Count), [Rock Paper Scissors](https://github.com/KrishnaRajule/cv/tree/main/Rock%20Paper%20Scissors), [SURF](https://github.com/KrishnaRajule/cv/tree/main/SURF). I have been curating and debugging the codes and trying to make them work. I had also used the opportunity to fork this [repository](https://github.com/Learn-Write-Repeat/Open-contributions)(#hacktoberfest) and was able to submit 4 PRs and complete the Hacktober Fest 2020 Challenge. Please visit this [link](https://github.com/Learn-Write-Repeat/cv) for Data Curation Updates.

- [Data Curation of NLP Project - TV Script Generation](https://github.com/KrishnaRajule/NLP-M4) : 

Curated NLP - TV Script Generation Project. Please visit the above link for updates.

**Comment by Ansuman9020** [comment]
- Initially we have downloaded and installed Bootstrap Studio application and learn and understand about it for designing static website using drag and drop feature of application.
- After that using any of the template from the bootstrap studio we did a portfolio page which includes the header, footer and different sections of the page.
- We gained knowledge more about the bootstrap studio.
- My second task was to understanding about SEO in webpages and then commented an issue in github.
- Next task was to design technical article for blog for DevIncept blog website and I have designed about pytube and pytxx3 article whose link is [Articles.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5439162/Articles.zip)
- Then I was given with a task of making timeline(flow type)  [homepage_1.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5439185/homepage_1.zip)
- Next task was for work individually as previously common task was given and from now individually we have to work so my task was to design authors page for blog website 
[blog.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5439200/blog.zip)
- Next we had to make a try for implementing "Search Feature" in static website in which we have tried but we didn't reach at any particular conclusion for it.

**Comment by reddymahendra52** [comment]
* Initially in the first week of the internship our main task was to learn Bootstrap Studio which has a drag and drop feature which is very useful and it saves a lot of time while implementing our ideas, since there are many inbuilt templates also.
The following tasks were done in first week:
    1. To make a product landing page.
    2. Understand basic SEO(Search Engine Optimization) 
    3. To create a personal portfolio:- [Portfolio](https://reddymahendra52.github.io/)
* Next week's task was to build a template for technical documentation page.
    1. [Initial template](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/5#issuecomment-699037863)
    2. Modifications were done according to standard template which was created by @akshayadme : [Changed template](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/6#issuecomment-699992131)
    3. Final template for technical documentation was created by @akshayadme which matched the main DevIncept site: [Final Template](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/7#issuecomment-700004581)
* Next task was to design Homepage and Finalising it with some added feature:
    1. [Initial homepage](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/8#issuecomment-700847964)
    2. In finalizing the home page my task was to add a **hit counter** to the page: [Template](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/9#issuecomment-701372158)
   3. You can read the implementation of Page counter [here](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/10#issuecomment-701937184)
* Next week's task was to design the blog page
   1. My task was to design the blog page for OpenCV articles. [Blog page](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/11#issuecomment-704297073)
   2. Next task was to implement a **"Search bar"** in the static web page: [Implementation](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/13#issuecomment-707836794)

**Comment by akrish4** [comment]
### Summary of my works:
 -  [Understanding Flask](https://github.com/Learn-Write-Repeat/Open-contributions/issues/175#issuecomment-704037512) 
 -  [ ML deployement using flask ](https://github.com/Learn-Write-Repeat/Open-contributions/issues/175#issuecomment-705300749)
 - [Salary Predictor Web App Using Flask ](https://github.com/Learn-Write-Repeat/Contribution-program/tree/master/ML_models_Flask/Ananthakrishnan%20Nair%20RS)
 - Categorized  all the python topics [here](https://docs.google.com/spreadsheets/d/1cf6XQe-ScXpanRqXMa5HpM4NUcKGX46ZTsVSZc2zILg/edit?usp=sharing)
 - **Data Curation of Python domain:** _Created 23 folders in the Python repository containing all the Python data - [link](https://github.com/Learn-Write-Repeat/python)_

**Comment by manvi-123894** [comment]
- Initially, we downloaded and installed Bootstrap studio and learned the basics of it. After that, we built a simple landing page to apply all the features of the Bootstrap studio we learned.

- After that, I learned the advanced features of Bootstrap studio, i.e., SEO. And then made a personal portfolio to apply all the advanced features of the bootstrap studio.

- After that, we designed a template for a technical blog website. [Technical Blog](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/5#issuecomment-699053879)

- After that, we designed a page for a technical article. [Python_Article](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/6#issuecomment-700172709)

- Then improved the previously made python blog page so that it looks like a part of the Devincept website. [Link](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/8#issuecomment-700771677)

- After that, we worked in a team for finalizing the home page for the Devincept website for which work was divided among the team members and I was supposed to design the latest blog section. [Link](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/9#issuecomment-701356389)

- Then I designed the page for Python blogs. [Link](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/11#issuecomment-704360921).

- After that, we were told to find a solution for implementing search functionality in a static web page for which I used vanilla javascript.  [Link](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/13#issuecomment-707658061).

- Then we were divided into different groups so that we could work with AI interns and deploy all the curated topics from the open contribution repository to the DevIncept website. I was supposed to work for the Machine Learning blogs. I've created some blog pages till now. Some of the pages that  I've created until now:

[ML BLOGS (2).zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5439795/ML.BLOGS.2.zip)

**Comment by HarshKhilawala** [comment]
**Summary of the Work :** 

* [Numpy Python Notebook](https://github.com/HarshKhilawala/Contribution-program/blob/master/intern-basics/Revisiting%20Numpy/Numpy.ipynb)
Created Python Notebook for quick revision to the important functions and methods of Numpy library in Python.

* [Revisiting Numpy Markdown File](https://github.com/HarshKhilawala/Contribution-program/blob/master/intern-basics/Revisiting%20Numpy/Revisiting%20Numpy.md)
Markdown File for brief introduction to Numpy Library in Python.

* [Introduction to OpenCV Python Notebook](https://github.com/HarshKhilawala/Contribution-program/blob/master/intern-basics/Introduction%20to%20OpenCV/OpenCV%20Introduction.ipynb)
Python Notebook for Introduction to basics of OpenCV Library in Python.

* [Introduction to OpenCV Markdown File](https://github.com/HarshKhilawala/Contribution-program/blob/master/intern-basics/Introduction%20to%20OpenCV/Introduction%20to%20OpenCV.md)
Brief explanation and list of various useful methods in OpenC

* [Car and Pedestrian Detection System](https://github.com/HarshKhilawala/Contribution-program/tree/master/intern-basics/Car%20and%20Pedestrian%20Detection)
Live Car and Pedestrian Detection System

**Comment by jaydhamale7** [comment]
**Summary of my works:**
Understanding Flask
ML deployement using flask
Next Word Prediction
Categorized all the python topics
Data Curation of Python domain: [https://github.com/Learn-Write-Repeat/python](url)

**Comment by chirag0821** [comment]
- At the begining, i have overviewed the working of bootstrap sudio and created an ecommerce website(static) using advanced tools in bootstrap studio.
LINK: (https://drive.google.com/u/0/uc?id=1wW9VUG2hMP39lh4552janfcuYeu1-esU&export=download)
- I have created my portfolio and added advanced SEO features to it.
LINK: (https://drive.google.com/u/0/uc?id=1wTNNoxDbdcQwZML39GVT9lG63FBmFGny&export=download)
- Designed logo for devincept.codes
LINK: (https://drive.google.com/u/0/uc?id=1wW9VUG2hMP39lh4552janfcuYeu1-esU&export=download)
- Created sample home page for devincept.codes
LINK: (https://drive.google.com/u/0/uc?id=1ccDJiWIycawmgoerI8k-asARiD81nHru&export=download)
- Created sample block page for NLP
LINK: (https://drive.google.com/u/0/uc?id=1V9koZmbSODKdX3TYfKiRuwP7f32Puxph&export=download)
- Created final block page for NLP
LINK: (https://drive.google.com/u/0/uc?id=1PFdP1wZ5kUcXmnd8g_WV-ZbcZYnCjx0u&export=download)

**Comment by neha2426** [comment]
-  [Understanding flask](https://github.com/Learn-Write-Repeat/Contribution-program/blob/master/ML_models_Flask/Kumari%20Neha/Understanding%20Model%20Deployment.md)

- [Iris classification]( https://github.com/Learn-Write-Repeat/Contribution-program/blob/master/ML_models_Flask/Kumari%20Neha/iris.py)

- [ Iris flask deployment](https://github.com/Learn-Write-Repeat/Contribution-program/blob/master/ML_models_Flask/Kumari%20Neha/app.py)

- [Added 16 folders in ML repository]( https://github.com/neha2426/ml)

- [Video analysis using opencv2](https://github.com/neha2426/Open-contributions/tree/master/Kumari_OpenCV_Video_Analysis)
