### ISSUE TITLE
FastAPI

### ISSUE THREAD

**Issue by arpit-dwivedi** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#17]
Understand basics of [Fast API from this documentation page](https://fastapi.tiangolo.com/).

In the comments, explain what its, advantages, and try the example give in documentation and share your experience.

**Comment by reddymahendra52** [comment]
* FastAPI is a  web framework  used for building APIs with Python 3.6+
* Advantages:
   1. Very high performance, 
   2. Reduced bugs
   3. Easy to use and learn
* I tried the example in the documentations i was able to implement the example by following the steps which were were given in the documentation.
* But apart from following the steps i was only able to understand a few part of the documents and i was not able to understand the main crux of the documentation or FastAPI.

**Comment by manvi-123894** [comment]
- FastAPI is a framework for developing web applications in Python. Advantages of FastAPI are:

1. Fast, very high performance 
2. Easy to learn and code
3. Minimize code duplication
4. Fewer bugs

- I tried to understand the example given in the documentation but was unable to understand it as I'm not familiar with the Python language.

**Comment by akshayadme** [comment]
FastAPI is a software framework for developing web applications in Python. Python's FastAPI framework enables engineers to rapidly build new applications by calling functions such as authentication through the Fast API.

Advantages of FastAPI :-

1. It gives very high performance when worked with Node.js and GO.
2. It reduces the 40% human developed error.
3. It is designed in a way that's easy to learn.
4. It gives results in JSON format which most popular in demand format for web applications.
5. FastAPI applications running under Uvicorn as one of the fastest Python frameworks available.

I'm not that good in python but I tried the example given in documentation and little bit I have understood FastAPI. It is good to know that FastAPI works good with Node.js and I am familiar with Node.js coz I'm working on it.
