### ISSUE TITLE
Adding 3 new Beginner Friendly Projects

### ISSUE THREAD

**Issue by arpit456jain** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#36]
I would like to add 3  Beginner Friendly Projects
Details :
1. Repository for amazing CSS effects -
https://github.com/arpit456jain/Amazing-Css-Effects
2.  Repository for Javascript projects -
https://github.com/arpit456jain/Amazing-Js-Projects
3.  Repository for Cool Frontend Templates.
https://github.com/arpit456jain/Cool-Front-End_Templates
Sample websites are-
https://arpit456jain.github.io/Amazing-Css-Effects/
https://arpit456jain.github.io/Amazing-Js-Projects/
https://arpit456jain.github.io/Cool-Front-End_Templates/

**Comment by ashutoshkrris** [comment]
Alright @arpit456jain 
Assigning it to you!

**Comment by arpit456jain** [comment]
thanks @ashutoshkrris i will make PR asap
