### ISSUE TITLE
Description is not in center and boxes are not uniform

### ISSUE THREAD

**Issue by arpit456jain** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#37]
![image](https://user-images.githubusercontent.com/55352601/125230410-591f7c80-e2f6-11eb-8f28-f04575c7f8b1.png)

**Comment by arpit456jain** [comment]
@ashutoshkrris can I make a PR ?

**Comment by ashutoshkrris** [comment]
Yeah @arpit456jain 
Can you please share the screenshot of the updated page here?

**Comment by arpit456jain** [comment]
![screencapture-127-0-0-1-5500-projects-html-2021-07-12-10_12_12](https://user-images.githubusercontent.com/55352601/125232141-a3eec380-e2f9-11eb-906e-698c8c231369.png)
