### ISSUE TITLE
Understanding Template

### ISSUE THREAD

**Issue by arpit-dwivedi** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#6]
Go through the template made by @akshayadme [here](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/5#issuecomment-699019182)

Good things in the template:

1. Informative Navbar and footer.
2. Center aligned blog left and right spaces can be used for other information, like references or similar posts.
3. Header size is enough to give the topic and author details, and not that big which takes the whole page.
4. Interactive and formal design (Code + information)

Try implementing the same things in your template, or build a new one like this.

**Comment by reddymahendra52** [comment]
* First I have to tell the template made by **@akshayadme**  is pretty good.
* Today's task was to redo the template previously made by us.
* I created a totally new template from scratch which satisfy the requirements.
* My template contains a header section with signup, login and search
* A body section where I used grid system.
* And a footer section with social links.
* I took ideas from Akshay's template and tried to enhance with putting an Author's info section and a Similar content's section.

[New Documentation Page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5292382/New.Documentation.Page.zip)

**Comment by Ansuman9020** [comment]
- I just added my contribution file to template.
- Added a login/signup page along with the contact page.



[Library.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5293058/Library.zip)

**Comment by manvi-123894** [comment]
- Today's task was to enhance our previously made template by taking inspiration from @akshayadme template.

[LearnPython.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5293964/LearnPython.zip)

**Comment by chirag0821** [comment]
- Today I added side bar to my previous template.
- Added some styling also
[updated template](https://drive.google.com/u/0/uc?id=1_kuneZ1rcVpmJiRZWE7vXFQwsUmzuwVL&export=download)
