### ISSUE TITLE
Designing Template to match main site

### ISSUE THREAD

**Issue by arpit-dwivedi** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#7]
Go through the main [Devincept](https://devincept.tech/).
Try to make your template as part of the site, i.e. color, logo, navbar, etc.

I am adding the bsdesign of the template page of the main site in case needed.

[DevInceptTemplate.bsdesign.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5289969/DevInceptTemplate.bsdesign.zip)

**Comment by akshayadme** [comment]
-  Today I have updated my previous template as a part of DevIncept site.

-  I have updated Navbar, Color, Logo, Font, Footer and some animations.

you can check [updated python.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5292519/updated.python.zip)
