### ISSUE TITLE
Home Page Designing 

### ISSUE THREAD

**Issue by akshayadme** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#8]
Today our lead is not present to assign any task to us for some of the reasons, so he told me to assign task to all of us.

So todays task is to create home page with the same template for blog site by taking the reference from the bsdesign given [DevInceptTemplate.bsdesign.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5297114/DevInceptTemplate.bsdesign.zip)

You can also take reference from my template also for designing home page  [Here](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/7#issuecomment-700004581)

**Comment by manvi-123894** [comment]
- Today's task was to update the previously made blog template and make it look like a part of the DevIncept website.
- I've updated the template and made the necessary changes.  
[Updated_Python_Template.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5300044/Updated_Python_Template.zip)

**Comment by reddymahendra52** [comment]
* Today's task was to create a home page.
* I used an inbuilt template from Bootstrap Studio and tried to make it similar to the reference DevIncept's site
* I made a few alterations to the inbuilt template and tried to enhance it.
[Home page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5300641/Home.page.zip)

**Comment by akshayadme** [comment]
- Today's task was to built a home page for previous template as a part of main site.
[home page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5300737/home.page.zip)

**Comment by chirag0821** [comment]
- Today's task was to create home page.
- I added navbar same as devincept home page.
- Added side bar for courses.
[Home page](https://drive.google.com/u/0/uc?id=1ccDJiWIycawmgoerI8k-asARiD81nHru&export=download)
