### ISSUE TITLE
Finalising Homepage

### ISSUE THREAD

**Issue by arpit-dwivedi** [Learn-Write-Repeat/Learn-Write-Repeat.github.io#9]
Today we'll try to finalize the homepage for this repository.

We'll be moving with [this template](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/issues/8#issuecomment-700856627) designed by Ashay which matches the main devincept site.

Tasks to be performed today:

1. As a newsletter option is added on top, try integrating with [Hubspot](https://app.hubspot.com/signup/marketing?hubs_medium=virality&hubs_campaign=hubspot-forms-virality&hubs_id=forms-branding-control&hubs_source=iotiot.in&intent=marketingFreeForms&opt_sidebar=forms&viralSourcePortalId=7109734). 
> Use any account for testing right now, we'll change it later with a genuine account.

2. Try finding a way, to show the number of views on a static web page. As it is normally done with a server to store data, it might be possible that there is a code available to embed in the page to count the number of visits.

3. Try implementing a cool [section like this] with 4 steps, to explain "what is contributor's program", just add the sections, content will be put later.

4. Add a section for latest blogs like "Choose what to learn" section in the template.

5. Designing a logo for this site (DevIncept.codes).

**Comment by Ansuman9020** [comment]
- I just tried with logo one.
![logo1](https://user-images.githubusercontent.com/52194650/94679320-8ab5f100-033d-11eb-8a7a-4214fe03eb1b.png)
![logo](https://user-images.githubusercontent.com/52194650/94679326-8c7fb480-033d-11eb-92ec-7c4627b884e2.png)

**Comment by manvi-123894** [comment]
- Today's task was to finalize the homepage of the devIncept website.
- The task was divided into 5 parts and I chose to do part 4 where I was supposed to make a latest blogs section for the website.
- For this, I used the responsive grid layout of bootstrap.
- For each blog, I used an image, subject heading so that the reader could know the subject the blog is related to at a glance, a 
  blog topic and a small description of the blog.
- I also added a hover effect on each column.
[Latest_Blog_Section.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5305337/Latest_Blog_Section.zip)

**Comment by reddymahendra52** [comment]
* Today's task was divided into different among the team mates
* My task was to  show the number of views.
* First here below shows the count whenever page is viewed or reloaded
[home page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5305270/home.page.zip)
* Second here shows the count for every unique visitor but we cannot style it
[home page hit.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5305282/home.page.hit.zip)
* I also tried to design the logo
![DevIncept codes](https://user-images.githubusercontent.com/61696212/94687694-3b29f200-034a-11eb-9cb6-852878ed1b8b.gif)

**Comment by akshayadme** [comment]
- Today I have completed home page design with some updates.
- I have implemented 3rd part of the today's task and also 1st part of the task.
- In the 3rd part I have designed a section of "what is contribution program" with elegant design.
- I have completed task attached here [updated home page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5309474/updated.home.page.zip)

**Comment by Ansuman9020** [comment]
- As I took 3rd part of today's task, I tried with 2 different style.
- In the homepage1 zip file, we can add icons, gifs,pics in the bigger circle present in the "what is contribution program" part.
[homepage.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5306602/homepage.zip)
[homepage1.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5306604/homepage1.zip)

**Comment by chirag0821** [comment]
- I created two logos for the page.
[logo1](https://drive.google.com/u/0/uc?id=1_aU-rWRmIjiN5UceP4DtfjambSGZJt9v&export=download)
[logo2](https://drive.google.com/u/0/uc?id=1APSEVxJRqh2QgF5tEeNhOJJhH6Y32Fck&export=download)

**Comment by Ansuman9020** [comment]
![logo](https://user-images.githubusercontent.com/52194650/94716663-d03de280-036c-11eb-90d6-70991d21948d.gif)

**Comment by akshayadme** [comment]
bsdesign of my template [devincept main page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5310068/devincept.main.page.zip)

Exported file my template [updated home page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5310709/updated.home.page.zip)

**Comment by reddymahendra52** [comment]
* I have updated the above exported file with counter using the count API
* Whenever we want to start from zero we can start it fresh using unique key or just changing **devIncept** name in the script 
   to something unique 

![Capture](https://user-images.githubusercontent.com/61696212/94791659-995fdf00-03f5-11eb-90cc-10432f359eca.PNG)

Updated file: 
[updated.home.page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5310840/updated.home.page.zip)

**Comment by Ansuman9020** [comment]
- Updated the site by adding "what is contribution" section, link provided by akshay.
[updated home page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5311000/updated.home.page.zip)

**Comment by manvi-123894** [comment]
- I've added the latest blog section in the template.
- In the footer, the icons were not aligned properly. So, I've aligned the icons centrally.
[devincept_home_page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5311066/devincept_home_page.zip)

**Comment by chirag0821** [comment]
- I created following logos which can match the home site.
[logos](https://drive.google.com/u/0/uc?id=1wW9VUG2hMP39lh4552janfcuYeu1-esU&export=download)

**Comment by akshayadme** [comment]
I have completed the final home page design.
Merged all team members design into it.

[Final home page.zip](https://github.com/Learn-Write-Repeat/Learn-Write-Repeat.github.io/files/5317767/Final.home.page.zip)
